import { describe, expect, it } from "vitest"
import { GameStore } from "../../src/domain/GameStore"
import { SaveManager, type StorageLike } from "../../src/domain/saves"
import {
  BEACH_ENEMIES, BEACH_SCRAP, ICHTHYOSAUR, ICHTHYOSAUR_ID, MEDUSA_SCHOOLS, MEDUSAS,
  OCEAN_ENEMIES, OCEAN_WORLD_SIZES, SCUBA_PRICE, TIGER_SHARK, TIGER_SHARK_ID, oceanObjective,
} from "../../src/domain/ocean"

function oceanStore(): GameStore {
  const store = new GameStore()
  store.selectCharacter("sheepwolf")
  store.beginVillageChapter()
  store.defeatEnemy("walrus-throne")
  store.setLocation("forest-village")
  store.beginOceanIntro()
  return store
}
function dive(store: GameStore): void {
  store.setLocation("beach")
  store.awardGears("diving-budget", SCUBA_PRICE)
  store.setLocation("mole-shop")
  expect(store.purchaseScuba()).toBe(true)
  store.setLocation("sea")
}
function storage(): StorageLike & { values: Map<string, string> } {
  const values = new Map<string, string>()
  return { values, getItem: (key) => values.get(key) ?? null, setItem: (key, value) => { values.set(key, value) }, removeItem: (key) => { values.delete(key) } }
}

describe("морская глава", () => {
  it("задаёт три больших мира, 20 роботов ближнего боя, 3 стаи и двух постоянных боссов", () => {
    expect(Object.values(OCEAN_WORLD_SIZES)).toEqual(Array(3).fill({ width: 4800, height: 1600 }))
    expect(BEACH_ENEMIES.filter(({ type }) => type === "robot-crab")).toHaveLength(12)
    expect(BEACH_ENEMIES.filter(({ type }) => type === "beach-albatross")).toHaveLength(8)
    expect(BEACH_ENEMIES.every(({ behavior, dropsGear }) => behavior === "melee" && dropsGear)).toBe(true)
    expect(MEDUSAS).toHaveLength(9)
    expect(MEDUSA_SCHOOLS).toHaveLength(3)
    expect(OCEAN_ENEMIES.filter(({ location, rank }) => location === "sea" && rank === "strong")).toHaveLength(12)
    expect(OCEAN_ENEMIES.filter(({ type }) => type === "spiny-fish")).toHaveLength(12)
    expect([TIGER_SHARK.hp, ICHTHYOSAUR.hp]).toEqual([90, 110])
    expect([TIGER_SHARK.respawnMs, ICHTHYOSAUR.respawnMs]).toEqual([null, null])
    expect(new Set(OCEAN_ENEMIES.map(({ id }) => id)).size).toBe(OCEAN_ENEMIES.length)
  })

  it("открывает пляж только после Моржа и разговора, море после покупки, Впадину после акулы", () => {
    const store = new GameStore()
    store.selectCharacter("wolf")
    store.beginVillageChapter()
    expect(store.beginOceanIntro()).toBe(false)
    store.setLocation("beach")
    expect(store.state.location).toBe("forest-village")
    store.defeatEnemy("walrus-throne")
    expect(store.canEnterOceanLocation("beach")).toBe(false)
    expect(store.beginOceanIntro()).toBe(true)
    expect(store.beginOceanIntro()).toBe(false)
    store.setLocation("beach")
    expect(store.state.ocean.beachVisited).toBe(true)
    store.setLocation("sea")
    expect(store.state.location).toBe("beach")
    dive(store)
    expect(store.state.location).toBe("sea")
    store.setLocation("trench")
    expect(store.state.location).toBe("sea")
    store.defeatEnemy(TIGER_SHARK_ID)
    store.setLocation("trench")
    expect(store.state.location).toBe("trench")
  })

  it("учитывает старые деньги только после посещения пляжа и сохраняет задание после траты", () => {
    const store = oceanStore()
    store.awardGears("old-budget", 40)
    expect(store.state.ocean.returnToMole).toBe(false)
    expect(store.purchaseScuba()).toBe(false)
    store.setLocation("beach")
    expect(oceanObjective(store.state)).toBe("Вернуться к кроту")
    store.setLocation("mole-shop")
    store.purchaseProduce("tomato")
    expect(store.state.gears).toBe(37)
    expect(store.state.ocean.returnToMole).toBe(true)
    expect(store.purchaseScuba()).toBe(false)
    store.awardGears("extra", 3)
    expect(store.purchaseScuba()).toBe(true)
    expect(store.state.gears).toBe(0)
    expect(store.purchaseScuba()).toBe(false)
    expect(store.state.equippedGadget).toBeNull()
    expect(store.state.inventory.filter(({ id }) => id === "scuba")).toHaveLength(1)
    store.setLocation("sea")
    store.takeDamage(10000)
    expect(store.state.location).toBe("forest-village")
    expect(store.state.ocean.hasScuba).toBe(true)
  })

  it("даёт ровно 40 шестерёнок за первое полное исследование пляжа", () => {
    const store = oceanStore()
    store.setLocation("beach")
    for (const pile of BEACH_SCRAP) {
      expect(store.collectBeachScrap(pile.id)).toBe(true)
      expect(store.collectBeachScrap(pile.id)).toBe(false)
    }
    for (const enemy of BEACH_ENEMIES) store.defeatEnemy(enemy.id)
    expect(store.state.gears).toBe(20)
    expect(store.state.ocean.returnToMole).toBe(false)
    for (const drop of store.state.enemyGearDrops) store.collectEnemyGearDrop(drop.id)
    expect(store.state.gears).toBe(40)
    expect(store.state.ocean.returnToMole).toBe(true)
    expect(store.state.enemyGearDrops).toHaveLength(20)
    store.defeatEnemy("sea-fish-1")
    store.defeatEnemy("trench-fish-1")
    expect(store.state.enemyGearDrops).toHaveLength(20)
  })

  it("провоцирует только одну стаю даже смертельным первым ударом и возрождает её целиком", () => {
    const store = oceanStore()
    const school = MEDUSA_SCHOOLS[0]!
    const [first, second, third] = school.enemyIds as [string, string, string]
    const now = Date.now()
    expect(store.isMedusaAggressive(first)).toBe(false)
    store.defeatEnemy(first, now)
    expect(store.isMedusaAggressive(second)).toBe(true)
    expect(store.isMedusaAggressive(MEDUSA_SCHOOLS[1]!.enemyIds[0]!)).toBe(false)
    expect(store.state.ocean.schools[school.id]!.respawnAt).toBeNull()
    expect(store.refreshMedusaSchools(now + 100_000)).toBe(false)
    expect(store.isMedusaDefeated(first)).toBe(true)
    store.defeatEnemy(second, now + 100_000)
    store.defeatEnemy(third, now + 101_000)
    store.deferMedusaRespawns(15_000)
    expect(store.state.enemyRespawnAt[first]).toBe(now + 176_000)
    expect(store.refreshMedusaSchools(now + 175_999)).toBe(false)
    expect(school.enemyIds.every((id) => store.isMedusaDefeated(id))).toBe(true)
    expect(store.refreshMedusaSchools(now + 176_000)).toBe(true)
    expect(school.enemyIds.every((id) => !store.isMedusaDefeated(id) && !store.isMedusaAggressive(id))).toBe(true)
    expect(school.enemyIds.every((id) => store.state.enemyRespawnAt[id] === undefined)).toBe(true)
    store.defeatEnemy(first, now + 177_000)
    expect(store.isMedusaDefeated(first)).toBe(true)
  })

  it("сохраняет частично уничтоженную агрессивную стаю при переходе и загрузке", () => {
    const store = oceanStore()
    dive(store)
    const enemyId = MEDUSA_SCHOOLS[1]!.enemyIds[0]!
    store.provokeMedusaSchool(enemyId)
    store.defeatEnemy(enemyId)
    store.setLocation("beach")
    const restored = new GameStore()
    expect(restored.restoreSerializedSession(store.exportSerializedSession())).toBe(true)
    expect(restored.isMedusaDefeated(enemyId)).toBe(true)
    expect(restored.isMedusaAggressive(enemyId)).toBe(true)
    expect(restored.isMedusaDefeated(MEDUSA_SCHOOLS[1]!.enemyIds[1]!)).toBe(false)
  })

  it("автосохраняет этапы, победы и финал без повторной награды или списания", () => {
    const store = oceanStore()
    const memory = storage()
    const saves = new SaveManager(store, memory)
    saves.bindAutosave()
    dive(store)
    expect(saves.read("auto")?.session.ocean.hasScuba).toBe(true)
    store.defeatEnemy(TIGER_SHARK_ID)
    expect(saves.read("auto")?.session.ocean.sharkCleared).toBe(true)
    store.setLocation("trench")
    expect(store.finishOceanChapter()).toBe(false)
    store.defeatEnemy(ICHTHYOSAUR_ID)
    expect(saves.read("auto")?.session.ocean.ichthyosaurCleared).toBe(true)
    expect(saves.read("auto")?.session.ocean.mechanismDisabled).toBe(false)
    expect(store.finishOceanChapter()).toBe(true)
    expect(saves.read("auto")?.session.ocean.mechanismDisabled).toBe(true)
    expect(saves.load("auto").ok).toBe(true)
    expect(store.finishOceanChapter()).toBe(false)
    expect(store.defeatEnemy(ICHTHYOSAUR_ID)).toBe(false)
    expect(store.defeatEnemy(TIGER_SHARK_ID)).toBe(false)
    expect(store.state.chapter).toBe(4)
    expect(store.state.inventory.filter(({ id }) => id === "coast-saviour-badge")).toHaveLength(1)
    expect(store.state.gears).toBe(0)
    expect(store.canEnterOceanLocation("sea")).toBe(true)
    expect(store.canEnterOceanLocation("trench")).toBe(true)
  })

  it.each([1, 2, 3, 4])("мигрирует версию %i после Моржа с новым вступлением и прежними покупками", (version) => {
    const source = oceanStore()
    source.awardGears("legacy-budget", 100)
    source.purchaseGadget("jetpack")
    const memory = storage()
    const saves = new SaveManager(source, memory)
    saves.save("slot-1")
    const envelope = JSON.parse(memory.values.get("forest-detectives:save:v5:slot-1")!)
    envelope.version = version
    delete envelope.session.ocean
    memory.values.delete("forest-detectives:save:v5:slot-1")
    memory.values.set(`forest-detectives:save:v${version}:slot-1`, JSON.stringify(envelope))
    const restored = new GameStore()
    const restoredSaves = new SaveManager(restored, memory)
    expect(restoredSaves.load("slot-1").ok).toBe(true)
    expect(restored.state.chapter).toBe(4)
    expect(restored.state.location).toBe("forest-village")
    expect(restored.state.ocean.introSeen).toBe(false)
    expect(restored.state.gears).toBe(73)
    expect(restored.state.ownedGadgets).toContain("jetpack")
    expect(restored.state.walrusCleared).toBe(true)
    expect(restored.beginOceanIntro()).toBe(true)
    expect(restoredSaves.read("slot-1")?.version).toBe(5)
  })

  it("нормализует снежную главу при возвращении пешком и при загрузке в деревне", () => {
    const store = new GameStore()
    store.selectCharacter("fox")
    store.beginVillageChapter()
    store.setLocation("bird-pass")
    store.defeatEnemy("turtle-guardian")
    expect(store.state.chapter).toBe(2)
    store.setLocation("mountain-hollow")
    store.setLocation("wild-forest")
    store.setLocation("forest-village")
    expect(store.state.chapter).toBe(3)
    expect(store.state.entryFrom).toBe("wild-forest")
    const legacy = store.exportSerializedSession()
    legacy.chapter = 2
    const restored = new GameStore()
    restored.restoreSerializedSession(legacy)
    expect(restored.state.chapter).toBe(3)
    expect(restored.state.entryFrom).toBe("wild-forest")
    store.beginVillageChapter()
    expect(store.state.chapter).toBe(3)
    const beforeKnockout = { ...legacy, chapter: 2 as const, location: "bird-pass" as const }
    restored.restoreSerializedSession(beforeKnockout)
    restored.takeDamage(10000)
    expect(restored.state.chapter).toBe(3)
    expect(restored.state.location).toBe("forest-village")
    expect(restored.state.entryFrom).toBe("bird-pass")
    restored.defeatEnemy("walrus-throne")
    restored.beginVillageChapter()
    expect(restored.state.chapter).toBe(4)
  })
})
