import { describe, expect, it } from "vitest"
import { GameStore } from "../../src/domain/GameStore"

describe("игровая сессия", () => {
  it("начинается со снаряжением выбранного героя", () => {
    const store = new GameStore()
    store.selectCharacter("fox")
    expect(store.state.inventory).toHaveLength(1)
    expect(store.state.inventory[0]?.id).toBe("mirror")
    expect(store.state.stamina).toBe(110)
  })

  it("не добавляет одну улику дважды", () => {
    const store = new GameStore()
    store.selectCharacter("wolf")
    expect(store.collectClue("ribbon")).toBe(true)
    expect(store.collectClue("ribbon")).toBe(false)
    expect(store.state.puzzle.foundClues).toEqual(["ribbon"])
    expect(store.state.inventory).toHaveLength(2)
  })

  it("расходует и восстанавливает энергию в допустимых границах", () => {
    const store = new GameStore()
    store.selectCharacter("watermelon")
    store.updateStamina(2, true)
    expect(store.state.stamina).toBe(44)
    store.updateStamina(10, false)
    expect(store.state.stamina).toBe(100)
  })

  it("разрешает повторить вывод после ошибки и завершить дело", () => {
    const store = new GameStore()
    store.selectCharacter("rabbit")
    store.collectClue("parcel-print")
    store.collectClue("ribbon")
    store.collectClue("cardboard")

    expect(store.answer("tree").correct).toBe(false)
    expect(store.state.puzzle.completed).toBe(false)
    expect(store.answer("burrow").correct).toBe(true)
    expect(store.state.puzzle.completed).toBe(true)
  })

  it("сохраняет глобальный прогресс до принятия параллельных заданий", () => {
    const store = new GameStore()
    store.selectCharacter("sheepwolf")
    store.beginVillageChapter()
    store.collectLetter("letter-1")
    store.collectLetter("letter-2")
    store.collectLetter("letter-3")
    store.defeatEnemy("hare-1")
    store.collectPart("hare-1")

    expect(store.acceptQuest("lost-letters")).toBe(true)
    expect(store.state.quests["lost-letters"].status).toBe("ready")
    expect(store.acceptQuest("robot-parts")).toBe(true)
    expect(store.acceptQuest("robot-sweep")).toBe(true)
    expect(store.state.quests["robot-parts"].status).toBe("active")
    expect(store.state.quests["robot-sweep"].status).toBe("active")
  })

  it("сохраняет победы после поражения и восстанавливает героя в деревне", () => {
    const store = new GameStore()
    store.selectCharacter("wolf")
    store.beginVillageChapter()
    store.setLocation("wild-forest")
    store.defeatEnemy("wolf-1")
    const result = store.takeDamage(999)

    expect(result.knockedOut).toBe(true)
    expect(store.state.location).toBe("forest-village")
    expect(store.state.entryFrom).toBe("wild-forest")
    expect(store.state.health).toBe(store.state.maxHealth)
    expect(store.state.defeatedEnemies).toEqual(["wolf-1"])
  })

  it("запоминает вход, из которого герой пришёл в новую локацию", () => {
    const store = new GameStore()
    store.selectCharacter("rabbit")
    store.beginVillageChapter()
    expect(store.state.location).toBe("forest-village")
    expect(store.state.entryFrom).toBe("forest-clearing")

    store.setLocation("wild-forest")
    expect(store.state.location).toBe("wild-forest")
    expect(store.state.entryFrom).toBe("forest-village")

    store.setLocation("forest-mine")
    expect(store.state.entryFrom).toBe("wild-forest")
    store.setLocation("wild-forest")
    expect(store.state.entryFrom).toBe("forest-mine")
    store.setLocation("forest-village")
    expect(store.state.entryFrom).toBe("wild-forest")
  })

  it("хранит дедлайн возрождения обычных врагов, но не босса", () => {
    const store = new GameStore()
    store.selectCharacter("wolf")
    expect(store.defeatEnemy("hare-1", 1_000)).toBe(true)
    expect(store.state.enemyRespawnAt["hare-1"]).toBe(31_000)
    expect(store.defeatEnemy("hare-1", 5_000)).toBe(false)
    expect(store.state.enemyRespawnAt["hare-1"]).toBe(35_000)
    expect(store.state.totalEnemyDefeats).toBe(2)
    expect(store.state.enemyDefeatCounts["hare-1"]).toBe(2)
    expect(store.state.enemyGearDrops.map(({ id }) => id)).toEqual(["hare-1:1", "hare-1:2"])
    expect(store.collectEnemyGearDrop("hare-1:1")).toBe(true)
    expect(store.collectEnemyGearDrop("hare-1:2")).toBe(true)
    expect(store.collectEnemyGearDrop("hare-1:2")).toBe(false)
    expect(store.state.gears).toBe(2)
    expect(store.defeatEnemy("boar-3", 1_000)).toBe(true)
    expect(store.defeatEnemy("boar-3", 2_000)).toBe(false)
    expect(store.state.totalEnemyDefeats).toBe(3)
    expect(store.state.enemyRespawnAt["boar-3"]).toBeUndefined()
  })

  it("сбрасывает весь прогресс второй главы", () => {
    const store = new GameStore()
    store.selectCharacter("fox")
    store.beginVillageChapter()
    store.acceptQuest("lost-letters")
    store.collectLetter("letter-1")
    store.defeatEnemy("hare-1")
    store.reset()

    expect(store.state.character).toBeNull()
    expect(store.state.chapter).toBe(1)
    expect(store.state.location).toBe("forest-clearing")
    expect(store.state.foundLetters).toEqual([])
    expect(store.state.defeatedEnemies).toEqual([])
    expect(store.state.totalEnemyDefeats).toBe(0)
    expect(store.state.enemyDefeatCounts).toEqual({})
    expect(store.state.enemyGearDrops).toEqual([])
    expect(store.state.enemyRespawnAt).toEqual({})
    expect(store.state.quests["lost-letters"].status).toBe("available")
    expect(store.state.gears).toBe(0)
    expect(store.state.ownedGadgets).toEqual([])
    expect(store.state.completedHomeChallenges).toEqual([])
    expect(store.state.ownedBuildingMaterials).toEqual([])
    expect(store.state.produceAmmo).toEqual({ tomato: 0, cucumber: 0, "dense-tomato": 0, "large-cucumber": 0 })
    expect(store.state.equippedWeapon).toBe("melee")
    expect(store.state.errands["mushroom-hunt"].status).toBe("available")
    expect(store.state.resources).toEqual({ stone: 0, stick: 0, rope: 0, scrap: 0, iron: 0, diamond: 0 })
    expect(store.state.collectedResourceNodes).toEqual([])
    expect(store.state.hasPickaxe).toBe(false)
  })

  it("завершает деревню только после четырёх основных заданий", () => {
    const store = new GameStore()
    store.selectCharacter("sheepwolf")
    store.beginVillageChapter()
    store.acceptQuest("lost-letters")
    store.acceptQuest("robot-parts")
    store.acceptQuest("robot-sweep")
    store.acceptQuest("beaver-security")
    for (const id of ["letter-1", "letter-2", "letter-3"]) store.collectLetter(id)
    for (const [index, id] of ["hare-1", "hare-2", "hare-3", "hare-4", "wolf-1", "wolf-2", "wolf-3", "boar-1", "boar-2", "boar-3"].entries()) {
      store.defeatEnemy(id)
      if (index < 5) store.collectPart(id)
    }
    for (const id of ["lost-letters", "robot-parts", "robot-sweep"] as const) store.turnInQuest(id)
    expect(store.state.villageSaved).toBe(false)
    for (const room of ["floor", "launchers", "gas", "battery"] as const) {
      expect(store.completeBeaverRoom(room)).toBe(true)
    }
    store.awardGears("test-jetpack", 12)
    store.purchaseGadget("jetpack")
    expect(store.crossBeaverChasm()).toBe(true)
    expect(store.completeBeaverRoom("control")).toBe(true)
    expect(store.turnInQuest("beaver-security")).toBe(true)
    expect(store.state.villageSaved).toBe(true)
  })

  it("учитывает возрождённых робозверей в общем счётчике задания Совы", () => {
    const store = new GameStore()
    store.selectCharacter("fox")
    store.beginVillageChapter()
    store.acceptQuest("robot-sweep")
    store.acceptQuest("robot-parts")
    for (let count = 0; count < 10; count += 1) {
      store.defeatEnemy("hare-1", count * 31_000)
      store.collectEnemyGearDrop(`hare-1:${count + 1}`)
    }
    expect(store.state.defeatedEnemies).toEqual(["hare-1"])
    expect(store.state.totalEnemyDefeats).toBe(10)
    expect(store.questProgress("robot-sweep")).toBe(10)
    expect(store.state.quests["robot-sweep"].status).toBe("ready")
    expect(store.questProgress("robot-parts")).toBe(10)
    expect(store.state.quests["robot-parts"].status).toBe("ready")
    expect(store.state.gears).toBe(10)
    expect(store.state.enemyGearDrops).toHaveLength(10)
  })

  it("сохраняет контрольную точку и остаётся в доме Бобра после поражения", () => {
    const store = new GameStore()
    store.selectCharacter("wolf")
    store.beginVillageChapter()
    store.setLocation("beaver-house")
    store.completeBeaverRoom("floor")
    const result = store.takeDamage(999)
    expect(result.knockedOut).toBe(true)
    expect(store.state.location).toBe("beaver-house")
    expect(store.state.beaverHouse.checkpoint).toBe("floor")
    expect(store.state.health).toBe(store.state.maxHealth)
  })
})
